env:
    ND_SCANINTERVAL: 15m
    ND_LOGLEVEL: info
    ND_SESSIONTIMEOUT: 24h
    ND_ENABLETRANSCODINGCONFIG: "true"
    ND_MUSICFOLDER: /music
    TZ: America/Chicago
    PUID: 1026
    PGID: 100

persistence:
    config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: "nfs-config-navidrome-claim"

    music:
        enabled: true
        emptyDir: false
        mountPath: /music
        existingClaim: "nfs-music-claim"

ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
        # nginx.ingress.kubernetes.io/auth-url: "https://sso.pmcd.io/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "https://sso.pmcd.io/oauth2/start?rd=https://$host$request_uri"
    hosts:
        - host: navidrome.pmcd.io
          paths:
              - path: /
                pathType: Prefix
    tls:
        - secretName: navidrome-prod-tls
          hosts:
              - navidrome.pmcd.io
