env:
    TZ: America/Chicago
    PUID: 1026
    PGID: 100

persistence:
    config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: "nfs-config-ombi-claim"

ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body

    hosts:
        - host: ombi.pmcd.io
          paths:
              - path: /
                pathType: Prefix
    tls:
        - secretName: ombi-prod-tls
          hosts:
              - ombi.pmcd.io