# Default values for zwave2mqtt.

image:
    repository: homeassistant/home-assistant
    pullPolicy: IfNotPresent
    tag: 2020.12.1

# Enable devices to be discoverable
hostNetwork: true

# When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
dnsPolicy: ClusterFirstWithHostNet

# Enable a prometheus-operator servicemonitor
prometheus:
    serviceMonitor:
        enabled: false
    # interval: 1m
    # additionalLabels: {}


persistence:
    config:
        enabled: true
        emptyDir: false
        existingClaim: "nfs-config-homeassistant-claim"

ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
    hosts:
        - host: ha.pmcd.io
          paths:
              - path: /
                # Ignored if not kubeVersion >= 1.14-0
                pathType: Prefix
    tls:
        - secretName: homeassistant-prod-tls
          hosts:
              - ha.pmcd.io
addons:
    codeserver:
        enabled: true
        volumeMounts:
            - name: config
              mountPath: /config
        ingress:
            enabled: true
            annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
                nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
                nginx.ingress.kubernetes.io/auth-url: "https://sso.pmcd.io/oauth2/auth"
                nginx.ingress.kubernetes.io/auth-signin: "https://sso.pmcd.io/oauth2/start?rd=https://$host$request_uri"
            hosts:
                - host: code-ha.pmcd.io
                  paths:
                      - path: /
                        pathType: Prefix
            tls:
                - secretName: code-homeassistant-prod-tls
                  hosts:
                      - code-ha.pmcd.io
