replicaCount: 1

service:
    type: LoadBalancer # ClusterIP
    port:
        port: 1883
        name: mqtt
    websocketPort: 9001
    annotations: {}
    loadBalancerIP: 192.168.1.234

resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi

# customConfig:

monitoring:
    podMonitor:
        enabled: false
    sidecar:
        enabled: true
        port: 9234
        args:
            - "--use-splitted-config"
        envs:
            - name: MQTT_CLIENT_ID
              value: exporter
            - name: BROKER_HOST
              valueFrom:
                  fieldRef:
                      fieldPath: status.podIP
        image:
            repository: nolte/mosquitto-exporter
            tag: v0.6.3
            pullPolicy: IfNotPresent
        resources:
            limits:
                cpu: 300m
                memory: 128Mi
            requests:
                cpu: 100m
                memory: 64Mi
