apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-fetcher
  namespace: cron
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: registry-cred
          containers:
            - name: speedtest
              image: registry.pmcd.io/speedtest
              env:
                - name: INFLUXDB_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-secret
                      key: influxdb-server
                - name: INFLUXDB_USER
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-secret
                      key: influxdb-username
                - name: INFLUXDB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-secret
                      key: influxdb-password
          restartPolicy: OnFailure
