
replicaCount: 1

image:
  repository: oznu/homebridge
  tag: latest
  pullPolicy: IfNotPresent

config_ui_port: 8888
loadbalancer_ip: 192.168.8.201 # IP Address used to define the loadbalancer service

env:
  - name: UID
    value: "1026"
  - name: GID
    value: "100"
  - name: tz
    value: America/Chicago

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" 
  path: /
  hosts:
    - homebridge.pmcd.io
  tls:
   - secretName: homebridge-prod-tls
     hosts:
       - homebridge.pmcd.io

volumes:
  - name: homebridge
    persistentVolumeClaim:
      claimName: nfs-config-homebridge-claim

volumeMounts:
  - name: homebridge
    mountPath: "/homebridge"

resources:
  requests:
    memory: 2048Mi
    cpu: 1
  limits:
    memory: 4096Mi
    cpu: 5

nodeSelector: {}

tolerations: []

affinity: {}

