# Default values for home-assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: homeassistant/home-assistant
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: RollingUpdate

persistence:
  enabled: true
  existingClaim: nfs-config-homeassistant-claim
  accessMode: ReadWriteOnce
  size: 100Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
  path: /
  hosts:
    - ha.pmcd.io
  tls:
    - hosts:
        - "ha.pmcd.io" # Host to access nextcloud
      secretName: "ha-prod-tls" # Name of the certifciate (see kubectl get certificate -A)
