# Default values for nzbhydra2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/nzbhydra2
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1026"
  - name: PGID
    value: "100"

strategyType: RollingUpdate

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
    nginx.ingress.kubernetes.io/auth-url: "https://sso.pmcd.io/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.pmcd.io/oauth2/start?rd=https://$host$request_uri"

  path: /
  hosts:
    - nzbhydra.pmcd.io
  tls:
    - secretName: "nzbhydra-prod-tls"
      hosts:
        - nzbhydra.pmcd.io

persistence:
  enabled: true
  existingClaim: nfs-config-nzbhydra-claim
  accessMode: ReadWriteOnce
  size: 100Mi

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: nfs-config-nzbhydra-claim

volumeMounts:
  - name: config
    mountPath: "/config"
