replicaCount: 1

image:
  repository: linuxserver/ombi
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1026"
  - name: PGID
    value: "100"
  - name: "TZ"
    value: "America/Chicago"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
  path: /
  hosts:
    - ombi.pmcd.io
  tls:
    - secretName: "ombi-prod-tls"
      hosts:
        - ombi.pmcd.io

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: nfs-config-ombi-claim

volumeMounts:
  - name: config
    mountPath: "/config"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
