repositories:
  - name: patrickjmcd
    url: https://patrickjmcd.github.io/helm-charts

  - name: openfaas
    url: https://openfaas.github.io/faas-netes/

  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com/

  - name: jetstack
    url: https://charts.jetstack.io

  - name: drone
    url: https://charts.drone.io

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: metallb
    chart: stable/metallb
    namespace: kube-system
    set:
      - name: configInline.address-pools[0].name
        value: default
      - name: configInline.address-pools[0].protocol
        value: layer2
      - name: configInline.address-pools[0].addresses[0]
        value: 192.168.8.200-192.168.8.210

  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: kube-system
    values:
      - values/nginx-ingress.values.yml
      # - controller.image.repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm
      # - controller.image.tag: 0.25.1
      # - controller.image.falserunAsUser: 33
      # - defaultBackend.enabled:

  - name: oauth2-proxy
    chart: stable/oauth2-proxy
    namespace: kube-system
    values:
      - values/oauth2-proxy.values.yml

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: kube-system

  # - name: ha
  #   chart: stable/home-assistant
  #   values:
  #     - values/homeassistant.values.yml

  # - name: nodered
  #   chart: stable/node-red
  #   values:
  #     - values/nodered.values.yml

  - name: nextcloud
    chart: stable/nextcloud
    values:
      - values/nextcloud.values.yml

  - name: sonarr
    chart: patrickjmcd/sonarr
    values:
      - values/sonarr.values.yml

  - name: radarr
    chart: patrickjmcd/radarr
    values:
      - values/radarr.values.yml

  - name: lidarr
    chart: patrickjmcd/lidarr
    values:
      - values/lidarr.values.yml

  - name: nzbget
    chart: patrickjmcd/nzbget
    values:
      - values/nzbget.values.yml

  - name: nzbhydra
    chart: patrickjmcd/nzbhydra
    values:
      - values/nzbhydra.values.yml

  - name: ombi
    chart: patrickjmcd/ombi
    values:
      - values/ombi.values.yml

  - name: grafana
    chart: stable/grafana
    values:
      - values/grafana.values.yml

  # Open-FaaS

  # - name: openfaas
  #   chart: openfaas/openfaas
  #   values:
  #     - values/openfaas.values.yml

  # Drone
  - name: drone
    chart: drone/drone
    namespace: drone
    values:
      - values/drone.values.yml

  - name: drone-runner
    chart: drone/drone-runner-kube
    namespace: drone
    values:
      - values/drone-runner.values.yml

  - name: registry
    chart: stable/docker-registry
    namespace: kube-system
    values:
      - values/registry.values.yml

  - name: prometheus
    chart: stable/prometheus
    namespace: monitoring
    values:
      - values/prometheus.values.yml

  - name: unifi
    chart: stable/unifi
    values:
      - values/unifi.values.yml

  - name: ghost
    chart: patrickjmcd/ghost
    values:
      - values/ghost.values.yml
