apiVersion: v1
kind: Pod
metadata:
  name: psql
  namespace: homeauto
spec:
  containers:
  - name: psql
    image: postgres:alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always