apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connector
    component: cron-connector
  name: cron-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cron-connector
  template:
    metadata:
      labels:
        app: connector
        component: cron-connector
    spec:
      containers:
        - name: cron-connector
          image: zeerorg/cron-connector:v0.2.2
          env:
            - name: gateway_url
              value: "http://gateway:8080"
            - name: basic_auth
              value: "true"
            - name: secret_mount_path
              value: "/var/secrets/"
          volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      volumes:
        - name: auth
          secret:
            secretName: basic-auth
