replicaCount: 1

image:
  repository: linuxserver/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1026"
  - name: PGID
    value: "100"
  - name: TZ
    value: "America/Chicago"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  path: /
  hosts:
    - jellyfin.pmcd.io
  tls:
    - secretName: jellyfin-prod-tls
      hosts:
        - jellyfin.pmcd.io

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: nfs-config-jellyfin-claim
  - name: tv
    persistentVolumeClaim:
      claimName: nfs-tv-claim
  - name: movies
    persistentVolumeClaim:
      claimName: nfs-movies-claim
  - name: music
    persistentVolumeClaim:
      claimName: nfs-music-claim
  - name: videos
    persistentVolumeClaim:
      claimName: nfs-video-claim

volumeMounts:
  - name: config
    mountPath: "/config"
  - name: tv
    mountPath: "/data/tvshows"
  - name: movies
    mountPath: "/data/movies"
  - name: music
    mountPath: "/data/music"
  - name: videos
    mountPath: "/data/videos"

resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2048Mi
    cpu: 2

nodeSelector: {}

tolerations: []

affinity: {}
