replicaCount: 1

image:
    repository: strapi/strapi
    tag: latest
    pullPolicy: IfNotPresent

env:
    database_client: postgres
    database_port: 5432

# you must create a secret in the same namespace with the following keys:
#    - database_host
#    - database_username
#    - database_password
database_secret_name: strapi-secret

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    path: /
    hosts:
        - strapi.pmcd.io
    tls:
        - secretName: strapi-prod-tls
          hosts:
              - strapi.pmcd.io

volumes:
    - name: strapi-volume
      persistentVolumeClaim:
          claimName: nfs-data-strapi-claim

volumeMounts:
    - name: strapi-volume
      mountPath: "/srv/app"

resources:
    requests:
        memory: 128Mi
        cpu: 0.1
    limits:
        memory: 256Mi
        cpu: 0.5

nodeSelector:
  beta.kubernetes.io/arch: amd64

tolerations: []

affinity: {}