## influxdb image version
## ref: https://hub.docker.com/r/library/influxdb/tags/
image:
    repository: "influxdb"
    tag: "1.8"
    pullPolicy: IfNotPresent

serviceAccount:
    create: true
    name:
    annotations: {}

## Persist data to a persistent volume
##
persistence:
    enabled: true
    existingClaim: nfs-data-influxdb-claim

setDefaultUser:
    user:
        existingSecret: influxdb-auth

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
    requests:
        memory: 256Mi
        cpu: 0.1
    limits:
        memory: 1Gi
        cpu: 1

# Annotations to be added to InfluxDB pods
# podAnnotations:
#   "consul.hashicorp.com/connect-inject": "true"

ingress:
    enabled: true
    tls: true
    secretName: influxdb-prod-tls
    hostname: influxdb.pmcd.io
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    path: /