apiVersion: v1
data:
    password: ENC[AES256_GCM,data:nhEd0GynYz6TAPt5pSOZNg==,iv:6+7e0yVWiWKGvyv3lhOYXuaUNqMc6d8X5jdZh9x30Mk=,tag:zfHReLSLgdOUe7zjBA9Wag==,type:str]
kind: Secret
metadata:
    name: code-server-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-04T17:43:34Z'
    mac: ENC[AES256_GCM,data:NXCUNqfsy3Bn++05VIpQqpklUigHTtAuPU03k9i3cUcL/5ZAk3J/8R4h1+U+EXeGRnw2xH9KjoxYHFcoZkxXzBJUpnUezHrpo9NYUISkEJ+WCLuygKgIT1E6IIfejRBAwdSgYnrhy37KcnpjFYdjEckh2tIWDSSMMPC/ENhszlY=,iv:cs4OphAFj47rQK12A639irAagIrPe4ytzUkDJapRG7U=,tag:A4rdNSHSUYc/9pfd1bC1pw==,type:str]
    pgp:
    -   created_at: '2021-05-04T17:43:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAlMEddg6rWOPYw5bTGpCqN4/YBr0DjAMQUq9WQkvmJnra
            rO+Bjjqie5+QXpdsLbcWGRN4BwbPFAFaRbc5Sv7VlQPyn0oEKRXGumJYq7kHblwu
            7Ac/yWgDnl1GfhJWpJNxZrgtH1ZA32q0Ccb/+Ne1yC6FQxnpoI9/a0e6Pre7hfPw
            246HKi2aJiW5Y6coo5gLDFH3fMN4PjuxTkeFQrhkmifwpWaWw0XqiQo3Aoqkq382
            qP8zODf2tQM1fbddAU5Q5/CcO952lmqR2Jj2X81hihIyTX+YK60Bvk3f6El2E5tC
            6M4e5jzWPZjf89XGSdvyIwzMGExoixh+Sy+Nkz6XA05F6tY6eGJMTnx372s6npwP
            +sFXKK2QbUttZHC4of3lbHLq9pZEPUf3aVGsOrXnKIcoaR7Dx3GH6Hx46hRa8dBl
            LERRNvhO99GQ5z7cyg5h8htj7+WiCPSrgT2MWsqAhm0a50I2HIuly8ywukGtHq8F
            E7rh1bzp7NPNe6JqmwS3FjZee72J52NdxD0v+ydezQY9YAjycS5w2Pfswl4NYc8d
            1MgmHlg6frhZzeSpOAlDLailUoOrKn0Lu3D79rKz9npc356p4PWPVriBXTCQ/qpH
            DtJq4NiNv1v0HwmrZW9NpEjaNax09zaC/rTpwnvYsnabMwRqwU+SjMexFkTXjXLS
            XgHdxDsmnb/LdgPXTMhFVVUJ6eGntsZn9F5DO1UtvW36IZys/Mndu8Xg30IX+n+f
            4/yNihmmbyIW6LGBc0485bt10udO3ZsTu2EDnPmR33VDaYMslN7sFkqukG1ne8Y=
            =EACt
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-04T17:43:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAs28hrbX7oVFmMVdlgryBinWQ2DYF7OXdhUUvOoXOobNu
            J+d2rnOME/UNzS4m4ZU/ErnJuyqdkR5V6+t2BxMkbtV54FPrwh0MSdKn971Ur2xi
            X3qZAK8JQHGBpply/gfeUfgpRciZ9OCg75M1iWSnp9Y+wo1VNAQfvKiHvb7wWNVQ
            9Df4uWlGJbHO/BzJSR/GSa3e6Pk9tuEHcmE0B5iTwyb0jR0VtailgDslDjIu9B1D
            brxAML2d4KThip9by4TiaWVds9WHcbiR/hnj72M5SOPrPnQAwCwjxIMVObjNqOqE
            orEaxSNY7hu1H8ysPDPEEUFMCoexz4xeAjTJ6Lz8Rb4V4SrRg0QLNtWZS9Zn1Obz
            fKtC0gpaY4SnxeYVQzUonQovbXYrLjVwETcy13KaMgmvGizSMlP4OdUT4zaZtMr/
            18dIo4B9HNmafRXC+6F3c0abRe6ILXoCIaAW9Ul7/bt1PnilHmPdA7CE7xKhgKGL
            kjL2mr00su9dcnWr6efvnKtFGw69dI2pQWlGc0C3F5d5EnXDOOmhuOu9KfISmDTF
            woYBRXcBLmlt2pbDGxHzQ8gbhU2P75IQlGlUv2674hFsX6vDrBKPWTV0dwd4AJfN
            unElXekz/+s+5/W1UCQFy+wn0bSROu+wylau/t1mr9lpFOD895j94FVRDvnVgNHS
            XgGO7DsF5/a5SjAxKarWlZXJT0REOV4MszjcC3ZCe78+MBvi6I5Fyyr+itRQqIK4
            ZpaJbiMQAE1Dw37Q1Q3qQKBUZDm7veq3ALMbsPA5KuV0B4BiGRnbDppCN3jrmCU=
            =mJd3
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
