apiVersion: ENC[AES256_GCM,data:gvs=,iv:rb+rxMn9HmuC3asmPzqLvA12ktie7xyAOn1aWoyv79k=,tag:BkcQScaHgjquMxKzKUCZyw==,type:str]
data:
    COMMENTO_POSTGRES: ENC[AES256_GCM,data:LlzuFEnwI804XnYyfIfAz+ul/h6/5tgmGCJZUyyO96sgxDw6Dl47h76QrjfFzhj7GwMF9aMPJeALQ8Z99MDWmmolBpkkiI29HcnCraHNupGGJtj6VUmsco0huywD3eT3seyljh91JPLLXLHgmTKSr7jcLT2gTJkfH5ORBAKVwCxnzKnz,iv:vLRmpzZKdNheeUmqTE/e2ZvAcNTBx0TLymEixko/IEw=,tag:L5f9u5+BHPii3MNwfBd2ow==,type:str]
    COMMENTO_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:dc8tXq+u2c4mAoH3u4mq3fgZqN7y6VL6Qox+uw==,iv:FifV1CgESKIVTorgiUuiDcPteLw1IlzvirGOC+39daM=,tag:42HL2gdfEm9jhlgiYTK0uw==,type:str]
    COMMENTO_SMTP_HOST: ENC[AES256_GCM,data:JldNWJmNRKmWXA9e5VkrirG/2bw=,iv:HkXHi13J2EXBgh3tGk6ny3UKdRch0AkTJG9X87tBi6Q=,tag:+HbZmr9/O3yIAU5TBGvSPQ==,type:str]
    COMMENTO_SMTP_PORT: ENC[AES256_GCM,data:Kfykog==,iv:F5h6FwfGCID3s1TAlAhN9eLr68UHwzq147a5oSmPfw0=,tag:XSpWw1DkxC4c5zopMllNHQ==,type:str]
    COMMENTO_SMTP_USERNAME: ENC[AES256_GCM,data:Tp3J9gSaPnwePYFoQGMVKCGA1AG10Q7PCdck/Q==,iv:Ast91EZfC/MhGi3SuFgK3oZ9mGz0YE3WtggOdUlLx+c=,tag:bg6ox6StZTaX/pM0w5p+Pg==,type:str]
    COMMENTO_SMTP_PASSWORD: ENC[AES256_GCM,data:YGVQJvlGQcDMORDey100U3TrQJXOAVsE,iv:nV3cEPKh9g4Gbvl7eYwL100Y1eg6TFcWly+AoFGlANw=,tag:/3r7IUPlmlxSzbG3BIN5kQ==,type:str]
    COMMENTO_TWITTER_KEY: ENC[AES256_GCM,data:D75CvBaDQ9MDAcVzNNSAb7v5xmv8ATqOQB2Xy0FYb4MXrv91,iv:T5oSrIocdlBsqsJy8llmLQqf2JZB7RsO36xugTno98A=,tag:fodfsM0uY0C+cYM5fH3gpQ==,type:str]
    COMMENTO_TWITTER_SECRET: ENC[AES256_GCM,data:75n0WFatvIHqifu+0grrmBrjNt8LUgpRmzPEIWBIXjKfFiBSIeqPHXqq0n/yiE6d/HivKBGEQoUSTyC5GUT7dHSRMoE=,iv:W4547JjkVLrO8b8dOyPCSGRe2Fzln5dbpDjVt6jPSVc=,tag:CTNoBE25xf+pcilaJcFYhg==,type:str]
kind: ENC[AES256_GCM,data:kThGebB6,iv:dvnYdDP9JxQfbd8GNEpjWjoC2z59FQ6KtocPlPCPwYs=,tag:hkHQ1GdO7g850AJFJsO/uA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:3LEFAZuMGU19lcsP4g==,iv:GUbA1HlK0mv0t6GX37S7sNweCirN+uCH0qMiPfCqsK8=,tag:fQafK6maZkUGxNerVvPzxA==,type:str]
    namespace: ENC[AES256_GCM,data:akYerP+ryQ==,iv:VRsTFBJx/s73oiOzVQsRcmnIiORrkwP76Vcq2zNAK68=,tag:fskBMsoTsYkNIBtD8PaVVg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-03-13T20:44:25Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwHG5dVB+YIrs1X88VXHSqWpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzbPw00K3CqI4AiUHAgEQgDvs70Meh7xVSvOacVv02qiW8ogmJil3ZuribG/xt50/NEMTt6bsmup/QoMgl4RqLYsSCBp/F9aoktry2w==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-13T20:44:25Z'
    mac: ENC[AES256_GCM,data:gat4ZyvRFFtmkENUPAPpwkBoafrEGCl442wn/2weiWdcLZCPIH7yl3W8ln2Nb4dWtbAjADg/xuO58DMNyYeMXiYc89eVlGCrpPeOTrNvNJsQFX1H+6TYI3g2kj6Z7fg1Lfwu6rAmY40BQ5Jb4P45YDvumbh/NObFhRiYpTl0XPc=,iv:1iLTr+9Cbfu4Nn6GoRlYShz9eBJ5g3kigqCXyw+/gQs=,tag:9UahNLKDxnm+qE6OggUNbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
