apiVersion: v1
data:
    grafana-password: ENC[AES256_GCM,data:uoStuCNZlt6rv+aNwokDJA==,iv:UmbOllapnhmb7Xyp7hsjXbKpy9ga3ANCkMv3dl+Fyrw=,tag:Hg3aeaIAKudVhqzjCSBK2A==,type:str]
    grafana-user: ENC[AES256_GCM,data:dTtXWQ4B3pZJp54zsI+CjQ==,iv:unKH2CFEZ4yFqc5G1o3eN46k4uaTbRJ829gqyETYqkI=,tag:xjnSKsCVL1aWhXSQCx99RA==,type:str]
kind: Secret
metadata:
    name: grafana-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-04T17:43:39Z'
    mac: ENC[AES256_GCM,data:n9k11jGmuuXQpvMp74+NH2FpR2Z9D7NGf7ZkL/ms2SMi4F8rGArL0CA8KlLSJ3iSmRb323ayP3dilF+lo3t7BDCCzXHGniyMqx3ubTjAgZPr5WRE81vUeATAynGU6hCj9d4XViCV6KThBn4tn2VjEt2+Fz5BoOnzoIK32Qkkpmw=,iv:PK7XcFbJEnNtIdkVVNDDBWMhWXZoaWmC4L27cboKWOU=,tag:Y/EUHWTZ/8YjZtdtRieZEQ==,type:str]
    pgp:
    -   created_at: '2021-05-04T17:43:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAwUhupL3SxquoAH+9NQYZumoCuTmEfLGmO0koK3og9co0
            Mh+hSzqDrN6/tKpbH9k3GM5RgFqHInR+w7n13GOdFp5ZzgC/P/x1T+Xxwv0qLNyg
            lIrxJJp3Bt5p4pYTKBvdZPy04uaIUN49enXp/CGBc1DsI4wLsUNgG9coP7cu5m3o
            pY3HjevAkeWHqE+b+W3EqOGM++cWGZxdl/fO6xeGxlaPlKEy6GUROJ4l34aN4LDy
            NZeEUy8m9JUPi+JxuKmP4k1ZDp2RX2eH1FGbAq7jpW/87+WFiGgHOid7E48xS5Su
            G7PYfZ3+DRkgWS1TvlAx2bYIQddqjnWFQ2JrRGZvsJANx6wCDMPqU2VC11ZNjxXl
            zEanek9pdmiDIk36U/x6+0Hty8j1JZCE41EjMbxx1RVpGdCos2ojyNAFO4XsnYIs
            fGyFG5XXp6rSKYFUGgz1Lwj07DeRPshF8jkfgSyyGXAan1gbskl9fxq1N82pd+j0
            S+YTkcloDF4kg332oHokQQLlpug6iPfunMeuuS0Hau4vzc6KU6RYcSb4wOo24hUv
            cozToTe5NsL/CNDQGzPJnXK0+ioxsCixO8UYc1N0ouy7K7VTBvlN/DEqY4eb5Osm
            lyA29N2e11mcXFnBgczmJjtKkp3BQ6655vKg6nOlh06FPJAhtr4cew5bsTdlFL7S
            XAEJnYHchwz4EAsm5sHqop/hON3p0cGVGHoS6RewRUQW51iGfQ7x/adZrZWl0jUX
            XJ8iFZTjTVOp3Xzw66X5A5A072SuLLoa123VWwnMO6yrz7ERBdW3Vt8q3uyY
            =9bA0
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-04T17:43:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/9FvnN6nhStLHCs1kVtF8dAbKDVu3iWvhCl3XKrJU9/iwl
            6uMEqq13FW5E9oBqeHAZQ/C0z0RhsLgsTtI8x3wfMelxD7tW6sB1k0pOIJTswfbS
            SHbRV8CtQq/lA1TrghZzV0SiGRB7ZuEcZfMX2RnKDoxh6eXMq5iiI86/dgD+6sY+
            y/hspide8xp26Tg2FX8aUYMRsIjKGLsQoLdIQ3HITS4g446+O5XksYClAg/cYO9F
            W/VIe4TmsllHxoLTukOZUjdHUOiNJUgptQQwoiO6W5vnApdZZRI7pfvO+tS/epsH
            3h9VYi6lgpuI7Qc+PgytIJIVKLD6snB86hoy4X0//145P8AjoMJ6YWWOSjT2CRvI
            H2xhTaneXRCQn2L6s4xdeIBy55ob1B9d+fCDyuNLJS7ckAyeO7jJXsu34Sf5pqRX
            XNum6/8M1Wc4T5yAv6FCwotWPMqbpnh0vHLTsTKAaKglCN5L0nOXhyuovIJg5yfD
            mBOChMavfLCMYoustLUEYXzs2Z8h5McJ/gXKDDdqy7TdM+gbvBVdhSktREekW/+0
            W46lUBHKIXEHrbXt/CwREWnmkUBJXSLEXyqBoXpu4ansCEDNLUUkUbp42ZbAVLic
            iPKLVRP74d37TSCpbQMSICw0aHcygoqka/JHm6YmgBs1gy7acLsZyYQ0Fie3VX7S
            XAG6Z/OaZIuI056tfk9XoumIQaIw4ANjIcK5W87lP1hUTMEpowY9uPJvnbnrOonx
            TmUHsQ22iiOC/RD+ZxjX6KyvHSsv1Bf9LvtVATVdj2vhklABpWUcSoXqQN7m
            =nDNM
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
