apiVersion: ENC[AES256_GCM,data:8HM=,iv:ch+De3PInkOqFYU1CSpbQJDA4BnTTqo64H9nd+2atG0=,tag:16IU0lSqTIkZ4MyS10UAOA==,type:str]
data:
    influxdb-server: ENC[AES256_GCM,data:9N4E5X7eGYwInfoTl5DQAelewyusJl2+,iv:/fb0pebS6hVmgaP2Iq3IP3C6vsQNPNHTAyFe4LCaoyY=,tag:7eSHFS2OMaiYJ8gADwoufA==,type:str]
    influxdb-password: ENC[AES256_GCM,data:OLApIHCHX8s3kqUa,iv:SUG2Wcbgwz2LW4y8oT+nVihL1rhcHgHhzxDE1KB43o4=,tag:RYOalO2QjVK5sJ5bI80k8A==,type:str]
    influxdb-user: ENC[AES256_GCM,data:uTThlX46AFS5L5PVBPFbbQ==,iv:9r9HPvlEUWDIFRQRVYJ4h/Lmpi3c8OkBGlK3NjU/0n4=,tag:rBYWSQm9iKO+OlZM1tzT1A==,type:str]
kind: ENC[AES256_GCM,data:ZLLG2y85,iv:Q7Mq9qIMrCltorIJ6Ntk/Vl12uViBujdldh2fC3lMtk=,tag:dTZoqd3MWt4z2SP0O2Kq8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jX+uqy+Vrjl/cXmEVw==,iv:8i7zUmb8fP9ybFyUkLGdtF2PkIcaIq6CSwriOu5OeHg=,tag:3AwPfA7yZANP8LCHgeGbbQ==,type:str]
    namespace: ENC[AES256_GCM,data:clh1ixAZqe6/Fw==,iv:8kK37o9I30s2AbMMRMSlNK4mh5azgNn26+v9sN+ITBA=,tag:Q1kji2TkYj4HcQNG/FqA/g==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2020-12-07T01:22:35Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwFYxwxeX3eBVtVCMOKVMPI4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx4Fc+6Y+6ivgKNT6AgEQgDuVC6dWV1WBhCUagycGEweRVtjDGWrfwTYK4UrOmHp35FkBCSXIDeaI9oi8a9zHEEoxL2HQKYaPgD/eow==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-07T01:22:35Z'
    mac: ENC[AES256_GCM,data:kcFLLziRBD52x78o+F593eabveHFLeX1F+5atpxXo81U5ZICFXGFyBQRhqMciR84iuBCDNHjSQ4vHoDPN3f1Y22OouDj2kdbtdPEvmkFPYASFo+LWRhbjtawy2ohzN/Qqs/RqPEOAj2yIvWVQgq3NWdjPv5YMHbYRdmk54qZvHk=,iv:aL1UEbHa+52EvmviJwQwHUq+cGI1ytfWeLFupza63b8=,tag:bFTDW4BnnCkuMCRURq7tNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
