apiVersion: ENC[AES256_GCM,data:Gj0=,iv:5/wjQ0bVtX88qzsR7ZwC9f5IR0yRUyL/hLjK8tt2D7g=,tag:Uatdv2TdEWbNfs1Z7E2HUg==,type:str]
data:
    kcpl-password: ENC[AES256_GCM,data:XoThKS5vqC+GLJ409f44hA==,iv:WHzXm4Lums4ENRi5pE0DVbSbTfONg1geEQmjhcsVol4=,tag:buSIlxGq+VkcMkn9rfmDsg==,type:str]
    kcpl-username: ENC[AES256_GCM,data:Ang7CAbDvSTKScI+bL0SSj+WLd1E9i5b9t6V8A==,iv:IZ3kIeF2L649Yv+7YrvLc1V3H2Lt87EV9/ZXPi1W1Zc=,tag:ShRdKqsuLr0Jn6Mz1ZGtZA==,type:str]
    kcwater-password: ENC[AES256_GCM,data:3/Kc6FRUwegKKqC38iCzkrH9+2rtZzO4wQqwZw==,iv:RewVaMCYf4d1WV6+ylaJn1R8TOkgKjfm+i37LJiPRSY=,tag:RLpy9T5CfG1BhneY9Ehxxg==,type:str]
    kcwater-username: ENC[AES256_GCM,data:fbidGTWKz1PXw8qTa7k8ag==,iv:PoCrbDc4f/fasHZr8/z/ukBA+kVTXuE5xGWa9hDl9XM=,tag:yn52Lo+H9Dlw6otktpxbTw==,type:str]
kind: ENC[AES256_GCM,data:NQs/zNjd,iv:zUAPIA8Wk9Ik1pOiNWGTXTxp0xT1IKqINPHBV87yYY8=,tag:YabSKPlzogGPIO09ryPhBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NnQbhe1R1gVsdD6Q,iv:v9Wi2MD6rIFjOnpszXUXstv+JOAICG9t369hYjXegDA=,tag:YuXTROJO0yrrjZk0WIRt1w==,type:str]
    namespace: ENC[AES256_GCM,data:Ku+d6w==,iv:yIGCkvjah9xyan8FitvKG+GIyg1vuqyYnqqcD5gOdOw=,tag:zOFTGZ+mHDYO3+8Pcl3gVw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-03-13T20:44:27Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwHupDM7mqxPga6uA9EMpRbNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/MESG0kVsxDeFMSsAgEQgDt7bdDhQiALMyroTgQMFO7Iwm9GDj+vAsDMCgZtv+5x2Lk1Bb6FYZdkZi29C0Nf98NEi5yglXhIDcplAg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-13T20:44:27Z'
    mac: ENC[AES256_GCM,data:dBbF5dC102aVXtV4Gz7qAthfhDDMBzbXmt3bxRFEdmjYmvGy6A78qr+Pxr/sEaHcRGNQkzWqKv0132tATJUCvX4QRl//dzpDUIJ2xBfCTiodMzxlA3hsGtjTgY0tvqMDJ5bVv3HxouA+kp9pfmMLVP/9BCz1hLjXtYXl9GLQick=,iv:NbhxARsqffu3jH3uRpKg8JZxOX3U1V4/9TC5DngKa6o=,tag:9Z9PN58AtW7LybhjlTis7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
