apiVersion: ENC[AES256_GCM,data:XP8=,iv:lGe8omZdVJ3aYIcjPOqKtYvIqBYBo0deaejRYuSvgV0=,tag:mnyRdProqST/J+xn8Jwvag==,type:str]
data:
    kcpl-password: ENC[AES256_GCM,data:XfWXP3f6He+mI0+oi0UjNw==,iv:MUAZ2lqhBBpB+rNErW9jq6HUbjd23wrLzuO1XXX1KXk=,tag:A44z70Anb9XqEBF3tRl4FA==,type:str]
    kcpl-username: ENC[AES256_GCM,data:59tzKMOMbyEZhNetjIn6BLk453+DNaY3xTJkVA==,iv:JJwl+AEC8DJRmH33WdpUDcGPqPMUiRvYW7D6T/6Titw=,tag:I53Phg/7wyzLvOtlSzk6dQ==,type:str]
    kcwater-password: ENC[AES256_GCM,data:yEJKerUExmkiZwKmBvYnTYNZjkseS5MytdiXcQ==,iv:7Tq4rKsNmMh1Rzahxk/ngvGS3cfCcHhhtMSNW27pz7o=,tag:V/uLtYyNZMiJ2hxPIplAcg==,type:str]
    kcwater-username: ENC[AES256_GCM,data:ZVpadG/BUisuL1l1uy+Y9g==,iv:JKrOYz4Q1yavd8XS7zIuBnO+MXi4IktTI5xqn+tli1o=,tag:3imhgDdy3MIYKvxdP4TzlQ==,type:str]
kind: ENC[AES256_GCM,data:NGxIaurp,iv:avKRaAxj/OqpFjW8hGG5x0GYrq28xarTN2BYOa7YI3c=,tag:lT0/bvrUNQBC4exh5rEMFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:R2cbqzwu27OOK/FU,iv:jixhAp1XWBoNeUk/OLnfEvjsYZhjiuW4VWO+4Fj9++U=,tag:Qv4zhFGDeK9iqZBWdXXA0Q==,type:str]
    namespace: ENC[AES256_GCM,data:296D8A==,iv:fPp+5AlggB6U1YwBnx7C6eWjgafW3fGR7nF72oXavMQ=,tag:lOaCn/7kPQaoN4viEBP+Pg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2020-12-07T01:22:35Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwEWoG5s6TbTSqhPkEPC6vhVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxF+MPBg2nRDa0EzpAgEQgDsl12dFvfA3axy2uI7tv5qNEWSZ69hQOLSOA2wjlWu6YcyK0hctC2Q0GCoHZEUS4ZQlV0sLff+wsveZGw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-07T01:22:36Z'
    mac: ENC[AES256_GCM,data:4KBmKKhpzfjHik+uJmISd4LzTbfHX6K16wXDjamahlmB0uNWP8L9+uGrlEgUK8zJZVBtK5VEWmG0u35mSxJV2dYnPKbEn8Wmp9nIl6D6sZ3mRgsvJv1CZPIQhjAU/VLSup+gGHxqbtWFaSNF3zjxPcJnmsiKJgo1IYsZmaNjXNY=,iv:iMsSrER+kHTqi91OKlwWYAXTo4uzXsyRajzNne5z/XA=,tag:IVzP7aKwe2gNDd3NCYhkXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
