apiVersion: ENC[AES256_GCM,data:M2U=,iv:8VOHpcvXwrC/Dbmy0Pcpb83Kb1KNjAeZ3TIBkIHBlJI=,tag:AXjnkM12B4LO6f1gyrV3gw==,type:str]
data:
    kcpl-password: ENC[AES256_GCM,data:XFB+IHhe4axqOfQ+LB2EaA==,iv:La9boBu0q/lVi6MxZOgXwkrMTnWRaawbXAnlJvyVq94=,tag:oBQnB69Z/l6neHEhzTEAGw==,type:str]
    kcpl-username: ENC[AES256_GCM,data:To6hBmn83ORznT1Qvnhf37KLJmAGPgKQyhEbvQ==,iv:WaNpJa+DL5WdDf/v+8qXjRJ4R9qmO934PRUEBJtzSDI=,tag:uqCkY2BUVP/X8rnQp3BcbQ==,type:str]
    kcwater-password: ENC[AES256_GCM,data:YdEt6fm6KZCHrwNfFI25QOVBHQB6uCvUPsJrjA==,iv:Nh3j6naMXd4+jNjGucbisX+PWzPuUud97QbqQ62dN5s=,tag:yYD90I9l10Z0rcawXRa2XA==,type:str]
    kcwater-username: ENC[AES256_GCM,data:DFQZ9hRXRnirLTZjoc+WiQ==,iv:zRFUzpqPMZRDxO9WaDHQJrdwdhDi6AJSJtPMFd4ZSsM=,tag:pR0B6Twg3cvEX6eDfx57JA==,type:str]
kind: ENC[AES256_GCM,data:Hw7mwFTa,iv:Gw3qVlF8AS8Su/fjPZjRy6BYd02Sp5r0HwSfOl+JM8M=,tag:fharu7vJtMJY8U+OyWyIfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lOI+4Ojh90a0e05e,iv:DZt7wQ7vYl05JYpUTipkyDQUnt3X2f687k/6YXFtqCc=,tag:uMMD42mXfCl5WcOXQCYTyw==,type:str]
    namespace: ENC[AES256_GCM,data:Zbp+cA==,iv:uNJKwILpRDxjMqw6fkIPxkFZH5QRpedlRxU6pupyMk8=,tag:qVJqJ7Uz9/G+1ol4PoTmxg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-04-17T17:36:44Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwGiZWykzgrWNjECXeOKCPN1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMOkx0yrFejOpEyIEAgEQgDs9HS69e3zjWATXUAO6DvyFPq3yAJfVNIRYKD71F0SjZWP5dGZ6m9iIVqm9KSIoNUwOAO5HQR+IrwNeoA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-17T17:36:44Z'
    mac: ENC[AES256_GCM,data:cJ/XKrb28vEt7f4qPh91NElWfwSShI5kqTgaCfRo6qwxLNUrFKno07t0+6+DtWDA2PeEQECMus0DRB3vCfqgmkCJB8k4CL3mJB3/8RXJlnDMMjAOPufBK3sx9rmX8+ow8q6pvl6xqq7lTtz6dPXjC+eWVRdM4m+dI6g+paEeBig=,iv:9Q14RiG5arIIuTvtIFtYUEn/MnjPgsoOqf8ezZ8IsqM=,tag:5sqJVbuHBv+sflqN2XYWug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
