apiVersion: ENC[AES256_GCM,data:UAg=,iv:Z8DJBMGO4Ofe87DhCvZNnmnMcFIEc1tmH4ebTMALpZw=,tag:80fKfJPDrWtHURCT+jaBjA==,type:str]
data:
    kcpl-password: ENC[AES256_GCM,data:CnOUe0mnOwuVTCa6XplE1g==,iv:12wfO5LN+2lADQrMBh+1okMlNNkyJV2xymnVF0fAOhU=,tag:No/4t7qXE/gm2GtKirAa7w==,type:str]
    kcpl-username: ENC[AES256_GCM,data:FoWFI3bHbkU4Xp8aaKoXM0ivgZBOobGkEsR/4g==,iv:YLfgbCCAa8DktYTyfH8jfc6MOO+LSOkY7vuRUbksAHM=,tag:iLp2jgah0vW6VCrsrAEIWA==,type:str]
    kcwater-password: ENC[AES256_GCM,data:/YpTBCl8vNpcl794pPQlu1S7zM0TAp9qNxrdrg==,iv:odUG9BILA3IcZVJ98lNPw8zm8W0UQtPrFYCSp+vnrfY=,tag:8ob9ZsiwxuXRhiXvKN+fXw==,type:str]
    kcwater-username: ENC[AES256_GCM,data:KfXTQR5xL9oifrryXgKjyQ==,iv:p56Bt7YTyLbGoTTDsIK8Gftq3r9E4Maj8ySnzlUSaho=,tag:EBQyTPPI9U+5ivEiZUO2gA==,type:str]
kind: ENC[AES256_GCM,data:O14j+3TE,iv:4KSFQC3cJyurr7b8gJ7jee36G39NbmrPlJD34Q/9PnU=,tag:PCDEZxpqqyeyAxfYK1e5cg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RIOU/IvyXj6Rs9Uq,iv:3tIz37kIIokrsE0iMWBffzK7qS0NTOf7bFk/KIVzYow=,tag:WU8F4WSp5AW9deyo7dv+SQ==,type:str]
    namespace: ENC[AES256_GCM,data:98OCkQ==,iv:/BOU9+bAhzsRdU34dgDvWg7g2oaIV76b6KLHMyQUyqQ=,tag:LIbMw06LK5GJfI5jOBQwKQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-05-04T02:21:09Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwHH0B6lWw5FLTz/DREvQcCzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMShA8fIJRiGyJCF0CAgEQgDvuoEcmAzgiI4XGVdAY+qfqB4T+ZcwomGLvIIy86CVGbyJt4Nga4jZrwKiRczpdmmzlbWOZL33C0QaANw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-04T02:21:10Z'
    mac: ENC[AES256_GCM,data:VQYX5bVtRTcRwMlSOazUintqn5JE/PQYU5DT37LBZSCspjC1snBOoUcg3KJXeN7ZwdbYym5rES5DSlpgSZSDqIKyZzlZxYZCGvmG+6Y3rJ/E6fpKPxZ6lVknm007haBpAuLfrh9vio1U1usC+KEWyUJrrTh3yC9jiqxyFLj1wfw=,iv:TVapTn+g6k6Vsf4nCgKp0x+cl5kYbE/K979jajsdOSA=,tag:sBqSU9gGada11leI0OlepA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
