apiVersion: ENC[AES256_GCM,data:Euo=,iv:pqc00Q0iDxW9WZ4cfojD0M0By+zdWDbh2j0e6pxuq4c=,tag:+Zj3oT9SBshKUtnPYg2cjQ==,type:str]
data:
    metabase-uri: ENC[AES256_GCM,data:gBmuHSU9DS6nbAKcul75In7PCckYIJl055vrruzE5KJaMbTG4CYTsQGUKhiqC6Yw2hdjZ05Lb4PRjPy28ldEmpF739Snj5rsZUBEHqKKqlZM5ZDK6PY1pgE4DvwIXHLzL+2vnsPDCXLJFcpr,iv:j+SgwoZ2oeCDBk75OeY8XLehb3X8qx2x4iUshEMPLa4=,tag:tl+9TxRJzlmU0HX29bEF4A==,type:str]
kind: ENC[AES256_GCM,data:1IFSXNVF,iv:irRgzhZtmhnbfAKlr9q2BdlwXzNMDiMJsB0F4nWI3LA=,tag:CQ9J+sAubqnpvZJpJ7D8Mw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eK466vtEHOKcHtSkRCey,iv:MhqYS4iKYXTHnKPHbxs641J4udzgqjAzbOwXJvtMsD4=,tag:Xtt42QLbWPHux7erevKaNg==,type:str]
    namespace: ENC[AES256_GCM,data:bSPDJM5cYA==,iv:p8ct16ywXODPwlR39wXlSu9iBZKwaP3ltb2cLs2MdXA=,tag:Lxpz2zYTE2sMwH+pruadxg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2020-12-24T02:47:20Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwEPYfGqqKx00wROudFYuPI3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCTmPkEbgATy6xCUxAgEQgDurRqoG5U6gNZnm7iyg9QRqAVOa92M29qznAMZcTn81HBGMdsS7PRHlXnIxwKrm8bNMCSO5E+3IBZOnZg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-24T02:47:20Z'
    mac: ENC[AES256_GCM,data:PlOv0AIKXtdKAR4MRMg8Dsm6IGeowdxqE9FWDVD5/q9JHigzZl7YJGaMPi4IxLrfeCHgKP9iZosAeOK8vZHM1KbTYzc7fs8uEB2BEmpkXkuJU69C2rpGD4uye/r/KMjReP1SUJKOJV1oQXX6FxCACzEqASg6IvllNieXwG476Qw=,iv:ObTwMlUqnV+FYlGnxt2N5joY5lxuS2svqGht2krjgzI=,tag:15iaQYAYfvx3ovA7iLvgww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
