apiVersion: ENC[AES256_GCM,data:fj0=,iv:/8sL1NvNEPxRShL1b3v3PeCg1iY5QSOyUh9VC+idgzE=,tag:KyCfVfpnN/JOdpQ3Yy2L0g==,type:str]
data:
    password: ENC[AES256_GCM,data:HJQlvopWH0zrXiNYv3qkzA==,iv:p/LgqoeshPuSprlYQTJSdg2/FFMEaIit2Im11jDu83U=,tag:7rEn63NkvrdkL4RZdWyUVQ==,type:str]
    username: ENC[AES256_GCM,data:1SjRh4OovO9S1D9IAHzA0w==,iv:5COkbCrYUAaXGwGUPnfXHphCAxVZ21qAVbqwuIuF7CI=,tag:13gfHY4sY773sI1POAw7yw==,type:str]
kind: ENC[AES256_GCM,data:N9j2gU1n,iv:mrmEm5JqMwMoxj5xJlxQ5JVkdzZ6GjmpGOFM5Dx+b30=,tag:wUXK9wrld2xjfjaNuEztiw==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:zpPKY6aMqe1oamuwpuGVEQ==,iv:6Kmv7w1ClAKdGB4d7JE0n3oYOCfEuk0WgVi2cYfGPkY=,tag:+JQT6WHP4GyoONMSg0A06Q==,type:str]
    namespace: ENC[AES256_GCM,data:ERTqcpZgfQ==,iv:sZ3umJoDUiMB8lJogTPx2wfWjl0VLtCCBfah9XF2MXY=,tag:hgjlqpl/tLB1kn1vqfjSMw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-04-17T17:36:45Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwE075NLU8QVNsUnrCwjOiD7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOZZRPwK65+DFX6/HAgEQgDvS13xLEh2X5JQZyb/mvGaPnmQVEPGK9Af7C/YU9MctmrLjVKNjtnLPwzXN06aAVt9D2iPZvNUAZRaWdg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-17T17:36:45Z'
    mac: ENC[AES256_GCM,data:KGKrHe/3rz1BlyFfa+Ur6blwOkOqFGHIG++to+bhK4p5eYaxdziRK3i1ZDHjR7Hht+7y4x/uZd0K58k80Su8bHrxMEyui8VvPpRDQR1CjL2s+opZTIC8g9Umd8F+8ncGMfs08vYveogX+pepG9rFKICNR89zDeEoEehHFP8sxCY=,iv:JKLSo5Gqx/tQni7ztFM6HFR0eJ51GbMMP056nfQbAF4=,tag:u6uwT+a/KFHzUZeUnsgGow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
