apiVersion: ENC[AES256_GCM,data:BRI=,iv:jNs3hI04TXkRjWJtKM/QkB13UzaBqeUL1RK4GYGFvyM=,tag:Digy3FQHYAr2//9f7UvqpA==,type:str]
data:
    client-id: ENC[AES256_GCM,data:UeIx2qSJl5U3Y3LE00IVsb4V7QPabp4+0BHIXPgkRQpBWsXPZ4Vw656yubGOmq1LT2dZ71o9bFW+0u1llT22t/0WXtdJxsqINCnnvmhuH1opMBUNTkzKuPsO9pZ7stR0,iv:zYh0uq8jP9QpmOSiDB32OpZPnuopa2H1zz/j9D5PuU8=,tag:NH2R8zUpfzJ5eX+uawwfUA==,type:str]
    client-secret: ENC[AES256_GCM,data:u/p9w72y4LRjqbSfX1BPvvl4DS7WHTDsqmCfpHnaR80=,iv:tWZurqhTBS+PP3efvGJv9s2VfqdDXreNehqUhvje2zU=,tag:0mNY40vjLbL8V0v+MtLylg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:x6mF/fpLHednzUH5FDxdBfTVhEJxYIZ+EFMotB8wVnE=,iv:M/u5gx9zeuZeQ0q6pUQgH81rcG/M29KN4SFk/st1uAU=,tag:osMtRgdxuqmjy/ilQQf99Q==,type:str]
kind: ENC[AES256_GCM,data:fko2SSi7,iv:GQ9Dflm5np6aNdsX2hFKEssu4Ujt9xpu6M8aUeJ9PD8=,tag:1RpcLY6VI+b/2pBhKGjobw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I0+sOpqbdxzxNKrl0kH3xGH4,iv:ODIUv0GlxNRrh6BpTes7gUsfftNRzpBihOc4Aw5i45k=,tag:L0m1SbhfD4aQdb5gg3Sx7w==,type:str]
    namespace: ENC[AES256_GCM,data:MY49KQE81i6mBts=,iv:iRpqD+mZI/pAcb4uRGMC+pdwOdMNJvnLyW/XAqDBHjc=,tag:/yT4rTCF6hxhaf9AcyaVMQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-03-13T20:44:27Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwGZYbVNu8Gjh7WZrWaIdo2GAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7MQ5UfcwxdLSSv9dAgEQgDsSuJngodVGR125Xosa28jMdEl1/6vc6vMK5NXEwih5zV92twwczFGBoMhuwDxX+1IFolAHCf4/DRJK1A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-13T20:44:28Z'
    mac: ENC[AES256_GCM,data:27C9y+1m6hGo4UbA9l1uxggwozs7F6M/QejHAzG8dZwWW6aFfaZY4MqlXtt9iJyBG4gcz22JSabP00THkIevtvZwHDB7JwqB0LnREjn8Xh7sC2hRoyX+bkW0b0oDSDSyL9dl03SHvBPgZwiu1PQR1aZQjPtteXrgVPs4fRKY8Pc=,iv:osYNEB4DfMqh8HJxmN1jB1AnxwYuF7ZlZhAkmrWVf6M=,tag:lWV7M6LzdcQ23J+4fK2Exw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
---
apiVersion: ENC[AES256_GCM,data:5Ms=,iv:urs6/Ta0ru7Z4UmeCddEpVWmSV+82tZYKwXeCPy2OPM=,tag:xBeFelUT76w8WV2L+M+6SQ==,type:str]
data:
    client-id: ENC[AES256_GCM,data:2i5qAfDBjeSQTDzGvY2XzYGm+e0eLbsAVcEFMw==,iv:7i+6GrW48x9Gf6ZacnB9HjThomwXtTyEGYl8D1IG0OA=,tag:vpaTaJPZSHrTPWUrPE7Eww==,type:str]
    client-secret: ENC[AES256_GCM,data:md0lIDOzmdT+Otub8bDG6w1bHkmtofgfNiQmiR3GxAb7LpX5ERo9eodxG6urtY4DspIJJulZLzU=,iv:B9amKRPrbY3tNync5CAKRYR02cgRcxCCgYjq20mYo34=,tag:m4TKuVI6eazFeyWA0yQQwQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:m1lXRv9wkumMcMeKJA4YZGvm9gPg0XAefu9NR1v1GLM=,iv:tAkf6Mh9RLYgmHS06EHJGlI9wbYI3PouvID/5SABYvw=,tag:EqT2+8Hy32686F/U+jLjyg==,type:str]
kind: ENC[AES256_GCM,data:RSC6KELR,iv:1w4B9/sk5pVVUpIGTvHV0RAi42wvPU+qZLGeBXuCtwE=,tag:Dy1umkHhin2BU9f6AHBzEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MXifVxaw5vikwBfsLFg77UoCIi9ZrFvC2Q==,iv:1InE1sUTc+/MZF412skN+WURFHudDzEsI6jsFR7JGbI=,tag:KkxYRWtCsO6lpLNyq3G34A==,type:str]
    namespace: ENC[AES256_GCM,data:8a6dxFFfoqe8Wg8=,iv:Y60KNM0jRdW0Qv03RINjSxcvsmyQdA3w+3oIKlCCtYQ=,tag:ze8MEIbobQ+M5nf/Hsl+9A==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2021-03-13T20:44:27Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwGZYbVNu8Gjh7WZrWaIdo2GAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7MQ5UfcwxdLSSv9dAgEQgDsSuJngodVGR125Xosa28jMdEl1/6vc6vMK5NXEwih5zV92twwczFGBoMhuwDxX+1IFolAHCf4/DRJK1A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-13T20:44:28Z'
    mac: ENC[AES256_GCM,data:27C9y+1m6hGo4UbA9l1uxggwozs7F6M/QejHAzG8dZwWW6aFfaZY4MqlXtt9iJyBG4gcz22JSabP00THkIevtvZwHDB7JwqB0LnREjn8Xh7sC2hRoyX+bkW0b0oDSDSyL9dl03SHvBPgZwiu1PQR1aZQjPtteXrgVPs4fRKY8Pc=,iv:osYNEB4DfMqh8HJxmN1jB1AnxwYuF7ZlZhAkmrWVf6M=,tag:lWV7M6LzdcQ23J+4fK2Exw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
