apiVersion: ENC[AES256_GCM,data:12U=,iv:RVB1i65MzNN4dn86jqnXxNdqha1yMIEXw1ZU1/5t44Q=,tag:iSDrJi+8ekEkgkmBVnqkcA==,type:str]
data:
    client-id: ENC[AES256_GCM,data:S+tBNhrJG78v4bCLzb2o42tbPq8w+JzbZsDghsx8iz9R2o/1GqIDYI0bzNaP4HY/8RGfrSpCCsm9vNitEQ0YrfWXM4RsWsI8eCQzf1EWw6pqVlDpQGXb3I6NJ7b0QKdR,iv:Mjsvd4tdj7gJHD2zpXx6VQz01P79OOgDzEFAwZR2k4s=,tag:B4DF8Voy4jIQMpnEiRGL+w==,type:str]
    client-secret: ENC[AES256_GCM,data:Nz/b12L9GdQ9EFwyDPBIRjJl09l9YbZ8MeCukmIspXo=,iv:xhjW2YTCEjmBlwiuiX/pzAqfwGhLWkvxaIkNYMrhbpk=,tag:dRiosvYFwoB3R/I1PjhpVw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:K27WkeVZGYS56jQqessaLW06pAP7CUAk3GYzXlib+ao=,iv:/+b2Yyy09ejYSIi+CclWJ9P8Dldmgl+ho7iBgayfYqo=,tag:/W0scQfBnxh4b/1KV550xQ==,type:str]
kind: ENC[AES256_GCM,data:iaPkfxM+,iv:4hwduzfsBxhs4p7/OiWFUgNqJu4h1UhFbUg7OSZ0OAY=,tag:gvv8TWXerk+R8eZUg+Xy8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BTvOWF0N82vp27/rIQbdZLHE,iv:XA0dOblyP0afWvN46+cIDEkIXSrkgUDHwQMW3w2neT8=,tag:o+tR0kXcEjNI/9jG3iAQtQ==,type:str]
    namespace: ENC[AES256_GCM,data:E417LceACP0Z9c8=,iv:BSqHmeWKt1pWo7Vp27J+ceqkVmFPzYIC0IF02YnPBZM=,tag:GqPvl4PG667LUNHcrPKWvQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2020-12-07T01:22:36Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwF5PF6DgwRNT0YQkFdH8xoKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEIdNs1TlLX77AGcGAgEQgDtK5KosfhwzQJEU68Aqj7XCRm/NvkMdIe4uNl/vXphlM38ia29DnIugi+SOroPf026RgLRxnultJjokTQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-07T01:22:36Z'
    mac: ENC[AES256_GCM,data:jZGAFLxnm+12ztZisZ2r6+loCNpSW/Qwmo2gX8299BFcwsbKHOzBY2iEDOf5FVxVdR2OBrb8ZjrlCbuCe26lRM2MTfeWpSzgEvrlnL3wI/uv895mI8gczqTX1GQsY55pYyic9kYWLHW2oeyPXhwxYjoV3dwNeYq0uGJh22Zl5xQ=,iv:2k4th7w5RaWFaxywTnBNCxpjbXcQ9IJwUtClz+VGqaY=,tag:fk7xdSSXl3jlmttKrgAj/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
---
apiVersion: ENC[AES256_GCM,data:ggc=,iv:0YXqNIjgHYkfGfCHT7JEiCyLxxvR9ZtD6AKTGB/XvQk=,tag:wr08zfJ3ezonezBoT0o6fQ==,type:str]
data:
    client-id: ENC[AES256_GCM,data:I9GOeLxvzP5v2yytnSLbGq7HbNxq4ewFOfPa4w==,iv:DVi17PG4JDGU9gBphk/qq4QWoMXFGpqhLYbRVVqiW1s=,tag:if19R0x134CzfR3CxfzrPw==,type:str]
    client-secret: ENC[AES256_GCM,data:h9Q4rllAI5MY/DulKh6kR4hmU0YGVWb8fx/NUrnGwbhOCdosfHvoZDh4ePB6SY6kq9Gbw4extJY=,iv:RD7yWLQ9T5oCqssJ1SPvamt7aKIG4OXSRF70mdyMv5s=,tag:eSey5ANZKLDb52LyCL/4iw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:Iwmn/94IuIHoZdTH7a+nL22qbmZCwv6yoAL9nA6C+rY=,iv:Ra1UkLqTdRP4y+QG3TEhmiWpCJ1oGrUV0CVYevnKk/Y=,tag:GzeBOZcGX7sSxNQZGI2J1A==,type:str]
kind: ENC[AES256_GCM,data:rdUhGA2V,iv:BG8fmwLSRCR4abrVkKJl3xuScH65rJFbmFZS36Do7X4=,tag:+bs7nj3lRbUdmV6scsMPVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NdXKH3gNG02ggFKE/Dth9K5XhwSM6L2aJA==,iv:v5p4uMn+CLqj7X/CgKqCyqM2A3DblvmzKgjLcfhQZHE=,tag:R910Tn2QGKd926yV5g+dQQ==,type:str]
    namespace: ENC[AES256_GCM,data:0jMJIP7EJ1kIXSo=,iv:hEsqX1v0ch+PCg65zspuLlrRloalMwmGBwfx0guFTZ0=,tag:CRWTyB+kpQKTEZx58GtghA==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2020-12-07T01:22:36Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwF5PF6DgwRNT0YQkFdH8xoKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEIdNs1TlLX77AGcGAgEQgDtK5KosfhwzQJEU68Aqj7XCRm/NvkMdIe4uNl/vXphlM38ia29DnIugi+SOroPf026RgLRxnultJjokTQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-07T01:22:36Z'
    mac: ENC[AES256_GCM,data:jZGAFLxnm+12ztZisZ2r6+loCNpSW/Qwmo2gX8299BFcwsbKHOzBY2iEDOf5FVxVdR2OBrb8ZjrlCbuCe26lRM2MTfeWpSzgEvrlnL3wI/uv895mI8gczqTX1GQsY55pYyic9kYWLHW2oeyPXhwxYjoV3dwNeYq0uGJh22Zl5xQ=,iv:2k4th7w5RaWFaxywTnBNCxpjbXcQ9IJwUtClz+VGqaY=,tag:fk7xdSSXl3jlmttKrgAj/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
