apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:2Mc9R+MS8U4KqiKhLnlTBAlRIb1QW8PSsOhPEhUyTD8y3rmW8jv3lgp9NtF/gDU7cXuKA9McLoa1xgG1Dd9/KlIUUJzGKgM0BPl5X+H8AvJAqbEyDNxXRNSMVKmSDjZI,iv:o+SveUkyMtCtHAajFa/oQenNAMqyUabpcSejtaXHMWE=,tag:DSFWcx3aLU/NI5oEFNS8Yg==,type:str]
    client-secret: ENC[AES256_GCM,data:ICiB+48w+UOZTa3BoFQLFPVv0jBLfcS2dC9k3CU1JNA=,iv:XmwacmqIV7fKYjERRREMf7vBB27IlBFx/h9JBvdVCHI=,tag:/KY9hyn22Mfnin7IY/7ugg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:0mQps9aB3R+yCJQ++t6me4vpPjW4SjUxV0S7jVB7pFg=,iv:jAFIOIDh1AM9sTJ6ByVkLeB87FF1qz/7o9VFP+SwqqU=,tag:ioV0BhLqDvb2WEAh+AR/rQ==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-04T17:43:45Z'
    mac: ENC[AES256_GCM,data:CwkfkdG2lcASpAu1MQ3GdDPqrg8ppwXQpl1m4jAbJbKaIIm3mhcpaqZcGidYVV2bO8e5OrEtD03uYWhoV6J19ulwcrkgr6vAj02SNkm5YFgTbSZNqqEMO+mTmiiLEsHN6tOoykDwOuJB11FbY9goq3CY2UsIqDmCZdblECpAIM4=,iv:kFY/8U4ngt3tZV3BGNT3zNnshszqt2+vtpf/A+iPitA=,tag:WyNRfGoCDods/gxHWpMleQ==,type:str]
    pgp:
    -   created_at: '2021-05-04T17:43:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+PkQJFougQwruplHDdKuKQ8ymR7Bgrw/OCGbckwTgUO6v
            ff1+mSEbo/NMU+xSuabn7dL8MW8yxzS0FIsLLAxVwsXgaaxFNewFO/5n+5CxNUzG
            vXsQNVtAcEN/WW0ZE4dRLcUCw9071dTeYReJ+QIEq5BwTdX/qTtLCRpcVVA/wAJZ
            nxc7vBur2Kr6s8u6Bk2L0pDoXy1Wd+CPo15IqSStf5U9hNiQCTKkY8cjvrNcK81J
            Kpk+KXE9KtfxfRTFYwMu01hQZQPWgWcb/9w2dL1RAFvowK+WePzk/L2x1qcv0/Pm
            1Q0gZO7djmwnX+UjQ4fKQKSkyQC4qmly1jXkzr6UgnacWafgt5uJjmAtltgQAizq
            0ML6YcI7dhQv+vxTji5SIsHQkPtCtSv3Gse6nxB7n8uNL8h0g76KXdQdy9v/6od7
            M0sjNdB/3kL2wvM9H88tARlWwfZKjgsNlwi45vdtcDv3J3KkkRelmX4BWVLuoLgS
            CTAIMEeWhmvp6XjYT5NZhelgIGfc6X1wQPhr/7Owdjkjx1LNEJB2n5xyAPKRHhzE
            lOev5a8Sqmp7QzTtfiMdMNd2IBCA4i25Qx/rfhndxgStTgqwAyhFeLZxH3wfb3z9
            cbSTN1RHJCGMlfMRZzGIWxia4FLgogrCQrXSLBnQNVoM9u3JiJJDuTMYvRi5o4rS
            XAH9ubE8b/EGimwD98npVAPqzLUyXia+iJcQfnrqZbI3gqxYPJeZ7o4oAiFT5YM7
            BQOKToYUHneG4/iXRQnbgNSiVVkxULp53lAo06z+Oi5+hv09ZmeKQw0g5pyA
            =wM6S
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-04T17:43:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8Dq9bp8ahT42qQ7E5zwb27XNvdk9YFDiBU0xG8BNnx6HV
            NO4WDKPb6wKwChjjZzjdIqJ34F1P0fz0/9TUnDkdXy3Al5Q/vwTuV6NTSBk7GJYc
            baE1EbOkFA3hypycR4rO7y/IGDzbbS+2ZBSmiikHvXURboMfe2GfHaStCxOsLw6Y
            glsqH8tDnWcF1P+cOxXW43+Uf1TcInTjjhX2lmR1KrBNCzY19EVW8AIONzW1aabv
            I4MxRSMkj3s4/OmehpPEHs0L7aiH+xMQGTGyPXe79kWVlckm3OBVpzPKet3QtDm1
            DFx+0TALy9giubDk2YLdIaobMsap3s+GNqH19gvaIkTDRC1o1IoSJzcTYQEn/AL5
            S3eatIVK36QvgjP28slLNsAql6wkeOv5n+RPi+u7pajwwRpkcZkPkIPZ+cpjOD0H
            0e+erNY9aqIsIBxaMWyIhzeLnrKUzKBUd6relPIj8y3579jc0LPKxaQluqQNRhNI
            LCz7XxF4JRqmsjLD7soyXAjjZRAMLbbMnsiRW13t58cWJwEgpl7ZiEGCKeHIfkUr
            XyTC7i2Y/BI3/9wZq8C/Ld7/noyhlye9rpj4mL/Jt4apE6dS1zxBK/GIke7eNPHD
            l8XSUUlNBE11ua9fvhf2Z7g1zC7pdDciRH51bIN7ImlH8mvnjhtWS5mt8jWxvQrS
            XAEIiMJI9sGN0YqPbVMfRPoMWbu5mpb1V+vWtfK3ebCldRG1SOzBCH3GyNGv0kW7
            l4Lo5rt8d8m+9uA+uJa537MWQJdpKz2prZjHSqz1/qJmJAKfFkpxIVnMkXkK
            =F71S
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:Q70D8VFJh0gLwzlOJEtHt70ESJv2V/UFZolkFg==,iv:db9+IMWJZc4GS7kI6PiGeSixyDsM4GxSMx2Zvqqxky4=,tag:Oss0c1SLVzyQG25ORB3avA==,type:str]
    client-secret: ENC[AES256_GCM,data:hVfvX97rDDKhKab7otA1xPg6dubeQc5KOGuqjvei5vaQZi7YvF9zwVOgtul3tqZIYvkVeoJ5P08=,iv:EWjAq8djgD5TUf6z7xWTEj0yO1SygSgh9rBAM3OATSE=,tag:HLsjDNnzzgtxCmuQSu4fQQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:OB1Pih6/zSikIVyFA1hPXvIIgOpeXFqVaxFgvNOknNo=,iv:00NrtxP/iFtY1Fra3QKZ6piyBcwo/iNqLlYrZ01wbU4=,tag:F4gJsGDMTj9zNmuXrV8uvw==,type:str]
kind: Secret
metadata:
    name: github-oauth2-proxy-creds
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-04T17:43:45Z'
    mac: ENC[AES256_GCM,data:CwkfkdG2lcASpAu1MQ3GdDPqrg8ppwXQpl1m4jAbJbKaIIm3mhcpaqZcGidYVV2bO8e5OrEtD03uYWhoV6J19ulwcrkgr6vAj02SNkm5YFgTbSZNqqEMO+mTmiiLEsHN6tOoykDwOuJB11FbY9goq3CY2UsIqDmCZdblECpAIM4=,iv:kFY/8U4ngt3tZV3BGNT3zNnshszqt2+vtpf/A+iPitA=,tag:WyNRfGoCDods/gxHWpMleQ==,type:str]
    pgp:
    -   created_at: '2021-05-04T17:43:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+PkQJFougQwruplHDdKuKQ8ymR7Bgrw/OCGbckwTgUO6v
            ff1+mSEbo/NMU+xSuabn7dL8MW8yxzS0FIsLLAxVwsXgaaxFNewFO/5n+5CxNUzG
            vXsQNVtAcEN/WW0ZE4dRLcUCw9071dTeYReJ+QIEq5BwTdX/qTtLCRpcVVA/wAJZ
            nxc7vBur2Kr6s8u6Bk2L0pDoXy1Wd+CPo15IqSStf5U9hNiQCTKkY8cjvrNcK81J
            Kpk+KXE9KtfxfRTFYwMu01hQZQPWgWcb/9w2dL1RAFvowK+WePzk/L2x1qcv0/Pm
            1Q0gZO7djmwnX+UjQ4fKQKSkyQC4qmly1jXkzr6UgnacWafgt5uJjmAtltgQAizq
            0ML6YcI7dhQv+vxTji5SIsHQkPtCtSv3Gse6nxB7n8uNL8h0g76KXdQdy9v/6od7
            M0sjNdB/3kL2wvM9H88tARlWwfZKjgsNlwi45vdtcDv3J3KkkRelmX4BWVLuoLgS
            CTAIMEeWhmvp6XjYT5NZhelgIGfc6X1wQPhr/7Owdjkjx1LNEJB2n5xyAPKRHhzE
            lOev5a8Sqmp7QzTtfiMdMNd2IBCA4i25Qx/rfhndxgStTgqwAyhFeLZxH3wfb3z9
            cbSTN1RHJCGMlfMRZzGIWxia4FLgogrCQrXSLBnQNVoM9u3JiJJDuTMYvRi5o4rS
            XAH9ubE8b/EGimwD98npVAPqzLUyXia+iJcQfnrqZbI3gqxYPJeZ7o4oAiFT5YM7
            BQOKToYUHneG4/iXRQnbgNSiVVkxULp53lAo06z+Oi5+hv09ZmeKQw0g5pyA
            =wM6S
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-04T17:43:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8Dq9bp8ahT42qQ7E5zwb27XNvdk9YFDiBU0xG8BNnx6HV
            NO4WDKPb6wKwChjjZzjdIqJ34F1P0fz0/9TUnDkdXy3Al5Q/vwTuV6NTSBk7GJYc
            baE1EbOkFA3hypycR4rO7y/IGDzbbS+2ZBSmiikHvXURboMfe2GfHaStCxOsLw6Y
            glsqH8tDnWcF1P+cOxXW43+Uf1TcInTjjhX2lmR1KrBNCzY19EVW8AIONzW1aabv
            I4MxRSMkj3s4/OmehpPEHs0L7aiH+xMQGTGyPXe79kWVlckm3OBVpzPKet3QtDm1
            DFx+0TALy9giubDk2YLdIaobMsap3s+GNqH19gvaIkTDRC1o1IoSJzcTYQEn/AL5
            S3eatIVK36QvgjP28slLNsAql6wkeOv5n+RPi+u7pajwwRpkcZkPkIPZ+cpjOD0H
            0e+erNY9aqIsIBxaMWyIhzeLnrKUzKBUd6relPIj8y3579jc0LPKxaQluqQNRhNI
            LCz7XxF4JRqmsjLD7soyXAjjZRAMLbbMnsiRW13t58cWJwEgpl7ZiEGCKeHIfkUr
            XyTC7i2Y/BI3/9wZq8C/Ld7/noyhlye9rpj4mL/Jt4apE6dS1zxBK/GIke7eNPHD
            l8XSUUlNBE11ua9fvhf2Z7g1zC7pdDciRH51bIN7ImlH8mvnjhtWS5mt8jWxvQrS
            XAEIiMJI9sGN0YqPbVMfRPoMWbu5mpb1V+vWtfK3ebCldRG1SOzBCH3GyNGv0kW7
            l4Lo5rt8d8m+9uA+uJa537MWQJdpKz2prZjHSqz1/qJmJAKfFkpxIVnMkXkK
            =F71S
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
