apiVersion: ENC[AES256_GCM,data:Y+s=,iv:gRTIls7MA+xwcznZB5KeJEV7aElHaim9OTAGhmlZEWU=,tag:IV8SNrbI14+ZLhCwcifRfw==,type:str]
data:
    postgresql-password: ENC[AES256_GCM,data:eDGHTW+Bgj1GxGL/yQApDua7ggQMUSNe7HS4lXuvCisROvXJNzJKNeAnIHQ1YLbC,iv:2UvoyHDwNDGq1mozb3e8WFeKi7EV1POzS0bb0FoRZGA=,tag:qKzwrgAZiCBmW2FKpjn7zA==,type:str]
kind: ENC[AES256_GCM,data:HhvSiBkZ,iv:nde+hDNdaODMjyKx2cgElYJqi1TzdAYvoP9sd7PxdXk=,tag:P0DlwM6HMsbLMiJV0+YvUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mX1aStt3ss8k0QkjlPE1NnI=,iv:Eg9QrdF44yi4I/LQwXwWW79Gxe0k4n9VZ5nm+pJqATA=,tag:P00LzdGjfaKaXkmlYS/oHQ==,type:str]
    namespace: ENC[AES256_GCM,data:Prg1EwFJBw==,iv:1Cy5Yl53+ljGGWUn4IDNCra+gkr2gL1vClu+rbb0Ze4=,tag:IBQtW3PKoI+jHmc3fhr98w==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:724072041727:key/49d9739a-3d51-4ecb-a927-c7793472afde
        created_at: '2020-12-24T02:47:21Z'
        enc: AQICAHiVpLnGH5r4v6QqTkG0m4eQQKzUfxd/yE4UNkkAl9ngqwHo2OU2C4eAKXk8JFkBGIDNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMO+jAh2rkixLf9xsBAgEQgDvkRCMp/Ypykfxa9EpuvoS/h8SC/CREGCbsWiyMxzgH1Yh4VNb1PIS4D6WDDS10Uu2Sd4AeLL5R4t4tsg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-24T02:47:21Z'
    mac: ENC[AES256_GCM,data:aAwXUHj2iXntRT4aHqNGNa7AxK1RWx0wH1obhV4gXQd7wCTfMlqDNtUxfkesiWBc5ZAp9cW0xpt8tzG+6bMMBkjtIFcP0ZEPSZsF7Xtk91OtOr+k+1s4k2CNOnbKHfRou3ul1PSwR/RvYF6tJ1KmfpOwJ2WeRIjhcBUliFe7VFA=,iv:SGl2UEiceB1EZS1FjWlwQVmxOWBD3nGHUy5Ho0quCZw=,tag:qUJjqnuhFqESrvuIMugnyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
