## Image Settings
##
image:
    repository: "chronograf"
    ## default: quay.io/influxdb/chronograf
    tag: 1.8.8
    pullPolicy: IfNotPresent

service:
    replicas: 1
    type: ClusterIP

## Persist data to a persistent volume
##
persistence:
    enabled: true
    existingClaim: nfs-data-chronograf-claim

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
    requests:
        memory: 256Mi
        cpu: 0.1
    limits:
        memory: 2Gi
        cpu: 2

## Configure the ingress object to hook into existing infastructure
## ref : http://kubernetes.io/docs/user-guide/ingress/
## OPTIONALLY you can set .Values.ingress.secretName to set which secret to use
##
ingress:
    enabled: true
    tls: true
    hostname: chronograf.pmcd.io
    annotations:
        kubernetes.io/ingress.class: "nginx"
        secretName: chronograf-tls-cert
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-url: "https://sso.pmcd.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.pmcd.io/oauth2/start?rd=https://$host$request_uri"
    path: /
