image:
    repository: grafana/grafana
    tag: latest
    pullPolicy: IfNotPresent

ingress:
    enabled: true
    # Values can be templated
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
    path: /
    hosts:
        - grafana.pmcd.io
    tls:
        - secretName: "grafana-prod-tls"
          hosts:
              - grafana.pmcd.io

resources:
    requests:
        memory: 128Mi
        cpu: 0.1
    limits:
        memory: 512Mi
        cpu: 1.0

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
    type: pvc
    enabled: true
    existingClaim: nfs-config-grafana-claim
# Administrator credentials when not using an existing secret (see below)
adminUser: admin
# adminPassword: strongpassword

# Use an existing secret for the admin user.
admin:
    existingSecret: "grafana-auth"
    userKey: grafana-user
    passwordKey: grafana-password

## Grafana's primary configuration
## NOTE: values in map will be converted to ini format
## ref: http://docs.grafana.org/installation/configuration/
##
grafana.ini:
    paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
    analytics:
        check_for_updates: true
    log:
        mode: console
    grafana_net:
        url: https://grafana.net
    server:
        domain: grafana.pmcd.io
        root_url: https://grafana.pmcd.io
