- block:
    - name: create a token
      shell: echo $(hostname) $(date +%s) | shasum | base64
      register: tkn

    - name: Install k3s on first node
      shell: curl -sfL https://get.k3s.io | sh -s - server \
        --write-kubeconfig-mode 644 \
        --no-deploy servicelb \
        --no-deploy traefik \
        --token "{{ tkn.stdout }}"
        --cluster-init
      ignore_errors: True
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"

    - name: Grab kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes
      notify:
        - fix kubeconfig
  when: server_role == "first"
  tags:
    - bootstrap

- name: Install k3s on server nodes
  shell: curl -sfL https://get.k3s.io | sh -s - server \
    --server "https://{{ groups['k3s_firstnode'] | map('extract', hostvars, ['ansible_host'])| list | first }}:6443" \
    --token "{{ hostvars[groups['k3s_firstnode'][0]]['tkn']['stdout'] }}" \
    --no-deploy servicelb \
    --no-deploy traefik \
    --write-kubeconfig-mode 644
  ignore_errors: True
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  when: (server_role == "server") and (multi_master == true)
  tags:
    - bootstrap

- name: Install k3s on worker nodes
  shell: curl -sfL https://get.k3s.io | sh
  ignore_errors: True
  environment:
    K3S_TOKEN: "{{ hostvars[groups['k3s_firstnode'][0]]['tkn']['stdout'] }}"
    K3S_KUBECONFIG_MODE: "644"
    K3S_URL: "https://{{ groups['k3s_firstnode'] | map('extract', hostvars, ['ansible_host'])| list | first }}:6443"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  when: ((server_role == "agent") and (multi_master == true)) or ((server_role != "first") and (multi_master == false))
  tags:
    - bootstrap
