- name: Install k3s on first node
  shell:
    k3sup install \
    --user {{ hostvars[item]['ansible_ssh_user'] }} \
    --ip {{ hostvars[item]['ansible_host'] }} \
    --k3s-extra-args="--no-deploy traefik --no-deploy servicelb" \
    --ssh-key={{ ssh_key_location }} \
    --local-path={{ kubeconfig_path }}
    # -- cluster
  with_items:
    - "{{ groups['k3s_firstnode'] }}"

# - name: Install k3s on server nodes
#   shell: k3sup join \
#     --user {{ hostvars[item]['ansible_ssh_user'] }} \
#     --ip {{ hostvars[item]['ansible_host'] }} \
#     --server \
#     --k3s-extra-args="--no-deploy traefik --no-deploy servicelb" \
#     --server-user patrickjmcd \
#     --server-ip {{ groups['k3s_firstnode'] | map('extract', hostvars, ['ansible_host'])| list | first }} \
#     --ssh-key=~/.ssh/swarm
#   tags:
#     - bootstrap
#   with_items:
#     - "{{ groups['k3s_servers'] }}"

- name: Install k3s on worker nodes
  shell: k3sup join \
    --user pi \
    --ip {{ hostvars[item]['ansible_host'] }} \
    --server-user patrickjmcd \
    --server-ip {{ groups['k3s_firstnode'] | map('extract', hostvars, ['ansible_host'])| list | first }} \
    --ssh-key=~/.ssh/swarm
  with_items:
    - "{{ groups['k3s_agents'] }}"
  tags:
    - bootstrap
