- hosts: k3s_firstnode
  tasks:
    - name: get token
      register: tkn
      shell: "sudo cat /var/lib/rancher/k3s/server/node-token"

- hosts: k3s_agents
  tasks:
    - name: Check for uninstaller on worker nodes
      stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: st

    - name: Install k3s on worker nodes
      when: not st.stat.exists
      shell: curl -sfL https://get.k3s.io | sh
      environment:
        K3S_TOKEN: "{{ hostvars[groups['k3s_firstnode'][0]]['tkn']['stdout'] }}"
        K3S_KUBECONFIG_MODE: "644"
        K3S_URL: "https://{{ groups['k3s_firstnode'][0] }}:6443"

