- hosts: k3s_firstnode
  tasks:
    - name: display file contents
      register: contents
      shell: "sudo cat /var/lib/rancher/k3s/server/node-token"

- hosts: localhost
  connection: local
  tasks:
    - name: debug
      debug:
        msg: "{{ hostvars[groups['k3s_firstnode'][0]]['contents']['stdout'] }}"

    - name: Replace kubeconfig with correct address
      replace:
        path: ~/.kube/config
        regexp: "127.0.0.1"
        replace: "{{ groups['k3s_firstnode'][0] }}"
