- name: remove unnecessary packages
  become: yes
  apt:
    autoremove: yes
  tags:
    - apt

- name: Update all packages to the latest version
  become: yes
  apt:
    upgrade: dist
  tags:
    - apt

- name: set appropriate hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - hostname

- name: update hosts file
  become: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  tags:
    - hostname
