apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: homebridge
  labels:
    k8s-app: homebridge
    location: lan
  name: homebridge
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: homebridge
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: homebridge
      labels:
        k8s-app: homebridge
        location: lan
      name: homebridge
    spec:
      containers:
      - env:
        - name: tz
          value: America/Chicago
        - name: HOMEBRIDGE_CONFIG_UI
          value: '1'
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: '8888'
        - name: HOMEBRIDGE_INSECURE
          value: '1'
        - name: PUID
          value: ""
        - name: PGID
          value: "0"
        image: oznu/homebridge
        imagePullPolicy: Always
        name: homebridge
        ports:
        - containerPort: 51827
          name: homebridge
          protocol: TCP
        - containerPort: 8888
          name: homebridge-ui
          protocol: TCP
        volumeMounts:
        - mountPath: /homebridge
          name: homebridge
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: homebridge
        persistentVolumeClaim: 
          claimName: nfs-config-homebridge-claim
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    k8s-app: homebridge
  name: homebridge
spec:
  type: LoadBalancer
  ports:
  - name: homebridge
    port: 51827
    protocol: TCP
    targetPort: homebridge
  selector:
    k8s-app: homebridge
  externalIPs:
    - 192.168.8.201
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-ui
spec:
  type: ClusterIP
  ports:
  - name: homebridge-ui
    port: 80
    protocol: TCP
    targetPort: homebridge-ui
  selector:
    k8s-app: homebridge
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "homebridge-ingress" # Name of the ingress (see kubectl get ingress -A)
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
spec:
  tls:
    - hosts:
        - "homebridge.pmcd.io"
      secretName: "homebridge-prod-tls"
  rules:
    - host: "homebridge.pmcd.io"
      http:
        paths:
          - path: / 
            backend:
              serviceName: "homebridge-ui"
              servicePort: 80 
