repositories:
  - name: patrickjmcd
    url: https://patrickjmcd.github.io/helm-charts

  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com/

releases:
  # - name: unifi
  #   chart: stable/unifi
  #   values:
  #     - ../values/unifi.values.yml

  - name: ghost
    chart: patrickjmcd/ghost
    values:
      - ../values/ghost.values.yml

  - name: homebridge
    chart: patrickjmcd/homebridge
    values:
      - ../values/homebridge.values.yml

  - name: metabase
    chart: stable/metabase
    values:
      - ../values/metabase.values.yml
