---
- name: Add drone repository
  community.kubernetes.helm_repository:
    name: drone
    state: present
    repo_url: https://charts.drone.io

- name: Install drone helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: drone/drone
    name: drone
    release_namespace: drone
    values: "{{ lookup('file', 'files/values/drone.values.yml') | from_yaml }}"

- name: Install drone-runner helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: drone/drone-runner-kube
    name: drone-runner
    release_namespace: drone
    values: "{{ lookup('file', 'files/values/drone-runner.values.yml') | from_yaml }}"
