---
- name: Add patrickjmcd repository
  community.kubernetes.helm_repository:
    name: patrickjmcd
    state: present
    repo_url: https://patrickjmcd.github.io/helm-charts

- name: Install sonarr helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/sonarr
    name: sonarr
    release_namespace: media
    values: "{{ lookup('file', 'files/values/sonarr.values.yml') | from_yaml }}"

- name: Install radarr helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/radarr
    name: radarr
    release_namespace: media
    values: "{{ lookup('file', 'files/values/radarr.values.yml') | from_yaml }}"

- name: Install lidarr helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/lidarr
    name: lidarr
    release_namespace: media
    values: "{{ lookup('file', 'files/values/lidarr.values.yml') | from_yaml }}"

- name: Install nzbget helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/nzbget
    name: nzbget
    release_namespace: media
    values: "{{ lookup('file', 'files/values/nzbget.values.yml') | from_yaml }}"

- name: Install nzbhydra helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/nzbhydra
    name: nzbhydra
    release_namespace: media
    values: "{{ lookup('file', 'files/values/nzbhydra.values.yml') | from_yaml }}"

- name: Install ombi helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/ombi
    name: ombi
    release_namespace: media
    values: "{{ lookup('file', 'files/values/ombi.values.yml') | from_yaml }}"

- name: Install beets helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: patrickjmcd/beets
    name: beets
    release_namespace: media
    values: "{{ lookup('file', 'files/values/beets.values.yml') | from_yaml }}"
