---
- name: Add stable repository
  community.kubernetes.helm_repository:
    name: stable
    state: present
    repo_url: https://kubernetes-charts.storage.googleapis.com/

- name: Add loki repository
  community.kubernetes.helm_repository:
    name: loki
    state: present
    repo_url: https://grafana.github.io/loki/charts

- name: Install prometheus helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: stable/prometheus
    name: prometheus
    release_namespace: monitoring
    values: "{{ lookup('file', 'files/values/prometheus.values.yml') | from_yaml }}"

# - name: apply prometheus postinstall secrets
#   k8s:
#     state: present
#     src: "/tmp/secrets_postinstall/prometheus-alertmanager.configmap.yml"

- name: Install grafana helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: stable/grafana
    name: grafana
    release_namespace: monitoring
    values: "{{ lookup('file', 'files/values/grafana.values.yml') | from_yaml }}"

- name: Install loki helm chart
  ignore_errors: yes # needed to keep going
  community.kubernetes.helm:
    chart_ref: loki/loki-stack
    name: loki
    release_namespace: monitoring
    values: "{{ lookup('file', 'files/values/loki.values.yml') | from_yaml }}"
