---
- block:
    - name: Remove secret mounts
      mount:
        name: "/tmp/secrets"
        state: unmounted
      become: true # as root

    - name: delete secret folders
      file:
        path: "/tmp/secrets"
        state: absent
      become: true # as root
  name: cleanup secrets
  tags:
    - cleanup

- name: Create folders
  file:
    path: "/tmp/secrets"
    state: directory
  tags:
    - mount

- name: Mount directories
  mount:
    name: "/tmp/secrets"
    src: "{{ secrets_mount_point }}"
    fstype: nfs
    state: mounted
  become: true # as root
  tags:
    - mount

- name: Give the correct permissions to the secrets mount
  file:
    path: "/tmp/secrets"
    mode: 0777
    recurse: yes
  become: true # as root

- name: apply secrets
  k8s:
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "/tmp/secrets/secrets/*.yml"
  tags:
    - secrets
# - name: Remove secret mounts
#   mount:
#     name: "/tmp/secrets"
#     state: unmounted
#   become: true # as root
#   tags:
#     - cleanup

# - name: delete secret folders
#   file:
#     path: "/tmp/secrets"
#     state: absent
#   tags:
#     - cleanup
